### ISSUE TITLE
epage init error

### ISSUE THREAD

**Issue by chenhongen** [didi/epage#1]
**Describe the bug**
when I run 'epage init xx',It doesn't work.
By the way,the wechat QRcode expired(T T)
**Screenshots**
<img width="701" alt="init" src="https://user-images.githubusercontent.com/16499303/85119763-d7753080-b254-11ea-9541-b90d4c40ab7e.png">

**Desktop (please complete the following information):**
 - OS: win10
- node: 12.13.0

**Comment by tt-ghost** [comment]
> **Describe the bug**
> when I run 'epage init xx',It doesn't work.
> By the way,the wechat QRcode expired(T T)
> **Screenshots**
> <img alt="init" width="701" src="https://user-images.githubusercontent.com/16499303/85119763-d7753080-b254-11ea-9541-b90d4c40ab7e.png">
> 
> **Desktop (please complete the following information):**
> 
> * OS: win10
> * node: 12.13.0

Try again. The reason is that the folder name is wrong (`script/` --> `build/`)

```sh
epage init epage-demo2
```
