### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by chenhongen** [didi/epage#2]
**Describe the bug**
'vuedrag**g**able' spell mistake in the doc.

**Screenshots**
<img width="631" alt="10" src="https://user-images.githubusercontent.com/16499303/85190242-e9a0ae80-b2e8-11ea-82aa-619a877b7a22.png">

**Comment by tt-ghost** [comment]
> **Describe the bug**
> 'vuedrag**g**able' spell mistake in the doc.
> 
> **Screenshots**
> <img alt="10" width="631" src="https://user-images.githubusercontent.com/16499303/85190242-e9a0ae80-b2e8-11ea-82aa-619a877b7a22.png">
------
Fixed
