### ISSUE TITLE
希望一些widget能够支持缺省值，比如输入框，日期等

### ISSUE THREAD

**Issue by wqr2016** [didi/epage#3]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tt-ghost** [comment]
没有理解你说的意思 @wqr2016

**Comment by wqr2016** [comment]
> 没有理解你说的意思 @wqr2016

1. 比如年龄缺省值需要设置成30，这个就需要widget需要一个类似default的值。"default": 30,
2. 比如省市地区下拉列表框中，需要指定一个缺省值为“北京“。性别下拉列表框，缺省值可以设置为”男”。 "default": "M"

可以参照下面项目中的default：
https://json-editor.github.io/json-editor/

**Comment by tt-ghost** [comment]
> > 没有理解你说的意思 @wqr2016
> 
> 1. 比如年龄缺省值需要设置成30，这个就需要widget需要一个类似default的值。"default": 30,
> 2. 比如省市地区下拉列表框中，需要指定一个缺省值为“北京“。性别下拉列表框，缺省值可以设置为”男”。 "default": "M"
> 
> 可以参照下面项目中的default：
> https://json-editor.github.io/json-editor/

好的，这个问题我们先记下了，会在后续版本中更新，谢谢在问题中还附带了示例
