### ISSUE TITLE
epage-cli create package.json error

### ISSUE THREAD

**Issue by chenhongen** [didi/epage#4]
**Describe the bug**
The package.json generated by epage-cli is error.Due to the property's value contains prohect path.
```
{
  "name": "e:\2020\visual\epage-yh",
  "version": "0.1.0",
  "description": "Epage widgets",
  "author": "chengzi <ttghost@126.com>",
  "main": "./dist/e:\2020\visual\epage-yh.min.js",
...
```

**To Reproduce**
>  epage init xx
>  cd xx
>  npm i xx

**Screenshots**
![image](https://user-images.githubusercontent.com/16499303/86506265-66ab4800-be00-11ea-8d57-e43ac5ef7f73.png)
**Desktop (please complete the following information):**
 - OS: win10

**Additional context**

**Comment by tt-ghost** [comment]
will be fixed in the next version @chenhongen

**Comment by tt-ghost** [comment]
Try to install the latest `epage-cli` (v0.1.2).  @chenhongen 

```sh
npm i epage-cli@latest -g
```
